<?php

// Crear la tabla Espacios
$sql_create = "CREATE TABLE IF NOT EXISTS espacios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Modulo VARCHAR(10) NOT NULL,
    Espacio VARCHAR(15) NOT NULL,
    Etiqueta VARCHAR(40) NOT NULL,
    Capacidad_Exacta VARCHAR(10) NULL,
    Capacidad_Adecuada VARCHAR(10) NULL,
    Computadora BOOLEAN,
    Proyector BOOLEAN,
    Pantalla BOOLEAN,
    Cortina_Proyector BOOLEAN,
    Bocinas BOOLEAN,
    Cortina_Luz BOOLEAN,
    Pintarron BOOLEAN,
    Doble_Pintarron BOOLEAN,
    Camara BOOLEAN,
    Descripcion_Espacio VARCHAR(255) NULL,
    Equipo VARCHAR(255),
    Observaciones TEXT,
    Reportes TEXT
);";

if (mysqli_query($conexion, $sql_create)) {
    echo "<br>Tabla Espacios creada exitosamente";
} else {
    echo "<br>Error creando tabla Espacios: " . mysqli_error($conexion);
}

// Insertar datos en la tabla Espacios
$espacios = "INSERT INTO Espacios (Modulo, Espacio, Etiqueta, Capacidad_Exacta, Capacidad_Adecuada, Computadora, Proyector, Pantalla, Cortina_Proyector, Bocinas, Cortina_Luz, Pintarron, Doble_Pintarron, Camara, Descripcion_Espacio) VALUES

-- Edificio A

('CEDA', '0101', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Servicios Medicos'),
('CEDA', '0102', 'Oficina Administrativa' , 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Unidad de aspirantes'),
('CEDA', '0103', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Banco Santander'),
('CEDA', '0104', 'Oficina Administrativa' , 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Control Escolar'),
('CEDA', '0201', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Unidad de atención psicológica'),
('CEDA', '0202', 'Bodega', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Bodega'),
('CEDA', '0203', 'Aula', 51, '40 a 50', TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, ''),
('CEDA', '0204', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Oficina Servicio Social'),
('CEDA', '0205', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Practicas Profesionales'),
('CEDA', '0206', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Control Escolar'),
('CEDA', '0301', 'Aula', 50, '40 a 50', TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDA', '0302', 'Aula', 50, '40 a 50', TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDA', '0303', 'Aula', 50, '40 a 50', TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDA', '0304', 'Aula', 50, '40 a 50', TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDA', '0305', 'Bodega', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Bodega'),
('CEDA', '0306', 'Aula', 50, '40 a 50', TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDA', '0307', 'Aula', 50, '40 a 50', TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDA', '0308', 'Aula', 50, '40 a 50', TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDA', '0309', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Unidad de enseñanza incorporada'),

-- Edificio B

('CEDB', '0101', 'Bodega', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Bodega'),
('CEDB', '0108', 'Bodega', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Bodega'),
('CEDB', '0108A', 'Laboratorio', 14, '10 a 20', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDB', '0109', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Conferencias Audiovisuales. Salón con butacas.'),
('CEDB', '0110', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'USPI. Unidad de Seguridad Preventiva Integral.'),
('CEDB', '0201', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Departamento Políticas Públicas.'),
('CEDB', '0202', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Instituto de investigación en políticas públicas y gobierno.'),
('CEDB', '0301', 'Aula', 50, '40 a 50', TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDB', '0302', 'Aula', 42, '40 a 50', TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDB', '0303', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDB', '0304', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDB', '0305', 'Aula', 33, '30 a 40', TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDB', '0306', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Doctorado en gestión de paz y prevención de las violencias. (DGPPV)'),
('CEDB', '0307', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Centro para la calidad e innovacion de la educación superior. Cátedra UNESCO.'),
('CEDB', '0308', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Antigua coordinación de Gestión Ambiental,Ingeniería de Negocios y Tecnologías de la Información'),

-- Edificio C

('CEDC', '0101', 'Aula', 44, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDC', '0102', 'Aula', 46, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDC', '0103', 'Aula', 44, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDC', '0104', 'Aula', 38, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDC', '0105', 'Aula', 44, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDC', '0201', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDC', '0202', 'Aula', 58, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDC', '0203', 'Aula', 51, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDC', '0204', 'Aula', 52, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDC', '0205', 'Aula', 52, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDC', '0206', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDC', '0207', 'Aula', 44, '40 a 50', TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDC', '0208', 'Aula', 40, '40 a 50', TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDC', '0209', 'Aula', 45, '40 a 50', TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDC', '0301', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDC', '0302', 'Aula', 45, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDC', '0303', 'Aula', 54, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDC', '0304', 'Aula', 45, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, ''),
('CEDC', '0305', 'Bodega', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Bodega'),
('CEDC', '0306', 'Bodega', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Bodega'),
('CEDC', '0307', 'Aula', 52, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, ''),
('CEDC', '0308', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDC', '0309', 'Aula', 47, '40 a 50', TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, ''),
('CEDC', '0310', 'Aula', 48, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),

-- Edificio D

('CEDD', '0101', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Sala de Maestros. STAUdeG - Gestión Empresarial'),
('CEDD', '0102', 'Aula', 51, '40 a 50', TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, ''),
('CEDD', '0103', 'Aula', 53, '40 a 50', TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, ''),
('CEDD', '0105', 'Bodega', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Bodega'),
('CEDD', '0106', 'Aula', 48, '40 a 50', TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDD', '0107', 'Aula', 54, '40 a 50', TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, ''),
('CEDD', '0108', 'Aula', 51, '40 a 50', TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, ''),
('CEDD', '0201', 'Aula', 53, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDD', '0202', 'Aula', 51, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDD', '0203', 'Aula', 48, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDD', '0204', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDD', '0205', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Planilla Verde (EStudiantes)'),
('CEDD', '0206', 'Aula', 48, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDD', '0207', 'Aula', 46, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDD', '0208', 'Aula', 46, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDD', '0209', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDD', '0301', 'Aula', 47, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDD', '0302', 'Aula', 51, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDD', '0303', 'Aula', 47, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDD', '0304', 'Aula', 51, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDD', '0305', 'Aula', 49, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDD', '0306', 'Aula', 45, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDD', '0307', 'Aula', 54, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDD', '0308', 'Aula', 54, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDD', '0309', 'Aula', 51, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),

-- Edificio E

('CEDE', '0101', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Sala de Listas - Control Magisterial División de Gestión Empresarial.'),
('CEDE', '0102', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Sociedad de alumnas y alumnos - SOMOS (NARANJA).'),
('CEDE', '0103', 'Aula', 48, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, ''),
('CEDE', '0104', 'Aula', 43, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, ''),
('CEDE', '0106', 'Aula', 44, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, ''),
('CEDE', '0107', 'Aula', 41, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, ''),
('CEDE', '0108', 'Aula', 41, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, ''),
('CEDE', '0109', 'Aula', 42, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, ''),
('CEDE', '0201', 'Aula', 51, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, ''),
('CEDE', '0202', 'Aula', 48, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, ''),
('CEDE', '0203', 'Aula', 49, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, ''),
('CEDE', '0204', 'Aula', 51, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, ''),
('CEDE', '0205', 'Aula', 40, '30 a 40', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, ''),
('CEDE', '0206', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Taller de mantenimiento - Aulas y espacios tecnológicos'),
('CEDE', '0207', 'Aula', 48, '30 a 40', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, ''),
('CEDE', '0208', 'Aula', 50, '30 a 40', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, ''),
('CEDE', '0209', 'Aula', 48, '30 a 40', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, ''),
('CEDE', '0210', 'Aula', 47, '30 a 40', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, ''),
('CEDE', '0301', 'Aula', 49, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, ''),
('CEDE', '0302', 'Aula', 47, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, ''),
('CEDE', '0303', 'Aula', 48, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, ''),
('CEDE', '0304', 'Aula', 48, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, ''),
('CEDE', '0305', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, ''),
('CEDE', '0306', 'Aula', 49, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, ''),
('CEDE', '0307', 'Aula', 48, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, ''),
('CEDE', '0308', 'Aula', 48, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, ''),
('CEDE', '0309', 'Aula', 49, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, ''),

-- Edificio F

('CEDF', '0101', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Laboratorio de cómputo para los alumnos y prestamo de equipo.'),
('CEDF', '0103', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'División de Gestión Empresarial'),
('CEDF', '0104', 'Bodega', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Cocineta y Bodega de la División de Gestión Empresarial'),
('CEDF', '0105', 'Aula', 41, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, ''),
('CEDF', '0106', 'Aula', 45, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, ''),
('CEDF', '0108', 'Laboratorio', 42, '40 a 50', TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, 'Laboratorio de capacidad de 42 alumnos con 2 tv'),
('CEDF', '0201', 'Aula', 46, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, ''),
('CEDF', '0202', 'Aula', 49, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, ''),
('CEDF', '0203', 'Aula', 49, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, ''),
('CEDF', '0204', 'Aula', 49, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDF', '0205', 'Aula', 48, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, ''),
('CEDF', '0206', 'Aula', 46, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDF', '0207', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDF', '0208', 'Aula', 52, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDF', '0209', 'Aula', 48, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDF', '0301', 'Aula', 45, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDF', '0302', 'Aula', 47, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDF', '0303', 'Aula', 46, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDF', '0304', 'Aula', 49, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDF', '0305', 'Aula', 51, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDF', '0306', 'Aula', 46, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDF', '0307', 'Aula', 48, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDF', '0308', 'Aula', 48, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDF', '0309', 'Aula', 48, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),

-- Edificio G

('CEDG', '0101-A', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Coordinador de laboratorio.'),
('CEDG', '0101', 'Laboratorio', '32', '30 a 40', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Laboratorio de servicios turisticos'),
('CEDG', '0102', 'Bodega', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Pequeña Bodega.'),
('CEDG', '0103', 'Laboratorio', '32', '30 a 40', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Laboratorio de cocina'),
('CEDG', '0106', 'Bodega', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Pequeña Bodega.'),
('CEDG', '0107', 'Laboratorio', '32', '30 a 40', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Restaurante Gourmet y Laboratorio de Cocina.'),
('CEDG', '0108', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Nucleo de Laboratorios de Gastronomía.'),
('CEDG', '0109', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'División de Gestión Empresarial.'),
('CEDG', '0201', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Departamento de Administración.'),
('CEDG', '0202', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Departamento de Administración.'),
('CEDG', '0203', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Departamento de Administración.'),
('CEDG', '0206', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Investigaciones Turisticas.'),
('CEDG', '0207', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Turismo, recreación y servicio.'),
('CEDG', '0208', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Apoyo a Departamento de Administración.'),
('CEDG', '0301', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Departamento de Recursos Humanos.'),
('CEDG', '0302', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Departamento de Recursos Humanos.'),
('CEDG', '0303', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Laboratorio y sala de juntas.'),
('CEDG', '0306', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Departamento de Mercadotecnia y Negocios Internacionales.'),
('CEDG', '0307', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Sala de Maestros.'),
('CEDG', '0309', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, ''),

-- Edificio H

('CEDH', '0101', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Sala de profesores.'),
('CEDH', '0102', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Sala de consejo.'),
('CEDH', '0103', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Coordinación de apoyo a la titulación División de Contaduría.'),
('CEDH', '0104', 'Bodega', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Archivero'),
('CEDH', '0105', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Control Magisterial.'),
('CEDH', '0106', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Dirección de División de Contaduría.'),
('CEDH', '0202', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Departamento de Contabilidad.'),
('CEDH', '0203', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Departamento de Impuestos.'),
('CEDH', '0301', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDH', '0302', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDH', '0303', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDH', '0304', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDH', '0306', 'Laboratorio', 40, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, 'Laboratorio con 24 Equipos pero con capacidad de 40 alumnos.'),
('CEDH', '0307', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDH', '0308', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDH', '0309', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),

-- Edificio I

('CEDI', '0101', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Delegación Sindical CUCEA. SUTUdeG.'),
('CEDI', '0102', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Sociedad de alumnos y alumnas (Naranja),'),
('CEDI', '0103', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Area de servidores.'),
('CEDI', '0104', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Laboratorio de Cómputo.'),
('CEDI', '0105', 'Laboratorio', 32, '30 a 40', TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, 'Laboratorio de Finanzas.'),
('CEDI', '0106', 'Bodega', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, ''),
('CEDI', '0108', 'Laboratorio', 40, '40 a 50', TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, 'Laboratorio de Laboratorio de Contabilidad. Maestra Emerita. CP Y LAE Aurora Gonzales Sedano.'),
('CEDI', '0110', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Departamento de Impuestos.'),
('CEDI', '0201', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDI', '0202', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Departamento de Impuestos.'),
('CEDI', '0203', 'Laboratorio', 28, '20 a 30', TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDI', '0204', 'Laboratorio', 28, '20 a 30', TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDI', '0205', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDI', '0206', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, 'Laboratorio de Impuestos.'),
('CEDI', '0207', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDI', '0208', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDI', '0301', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDI', '0302', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDI', '0303', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDI', '0304', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDI', '0305', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDI', '0306', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDI', '0307', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDI', '0308', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDI', '0309', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),

-- Edificio J

('CEDJ', '0101', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Departamento de Auditoría.'),
('CEDJ', '0104', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Departamento de Finanzas.'),
('CEDJ', '0201', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDJ', '0202', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDJ', '0203', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDJ', '0204', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDJ', '0205', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDJ', '0206', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDJ', '0207', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDJ', '0208', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDJ', '0209', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDJ', '0301', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDJ', '0302', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDJ', '0303', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDJ', '0304', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDJ', '0305', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDJ', '0306', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDJ', '0307', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDJ', '0308', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDJ', '0309', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, ''),

-- Edificio K

('CEDK', '0102', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Departamento de Economía y Sociedad.'),
('CEDK', '0102-A', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Sala de listas de División de Economía y Sociedad'),
('CEDK', '0109', 'Bodega', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Área de intendencia.'),
('CEDK', '0110', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Antigua coordinación de Administración Gubernamental y Políticas Públicas.'),
('CEDK', '0111', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Plataforma de Economía de Jalisco. Área de investigación y oficina de becarios.'),
('CEDK', '0114', 'Laboratorio', 28, '20 a 30', TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDK', '0114A', 'Laboratorio', 28, '20 a 30', TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, ''),
('CEDK', '0115', 'Bodega', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Área de intendencia.'),
('CEDK', '0201', 'Bodega', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Área de intendencia.'),
('CEDK', '0202', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Sociedad de Alumnos.'),
('CEDK', '0203', 'Aula', 49, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDK', '0204', 'Aula', 45, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDK', '0205', 'Aula', 48, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDK', '0206', 'Aula', 48, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDK', '0207', 'Aula', 49, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDK', '0208', 'Aula', 49, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDK', '0209', 'Aula', 49, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDK', '0210', 'Aula', 49, '40 a 50', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDK', '0302', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Departamento de Economía.'),
('CEDK', '0303', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Sala de seminarios. División de Economía y Sociedad.'),

-- Edificio L

('CEDL', '0101', 'Laboratorio', 28, '20 a 30', TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDL', '0102', 'Laboratorio', 28, '20 a 30', TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDL', '0103', 'Laboratorio', 28, '20 a 30', TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDL', '0104', 'Laboratorio', 24, '20 a 30', TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDL', '0105', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'GESTEC.'),
('CEDL', '0108', 'Laboratorio', 24, '20 a 30', TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDL', '0109', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Sala de maestros. Delegación División de Economía y Sociedad.'),
('CEDL', '0201', 'Laboratorio', 24, '20 a 30', TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDL', '0202', 'Laboratorio', 47, '20 a 30', TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDL', '0204', 'Laboratorio', 24, '20 a 30', TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDL', '0205', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Oficina de investigadores.'),
('CEDL', '0206', 'Laboratorio', 24, '20 a 30', TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDL', '0207', 'Laboratorio', 24, '20 a 30', TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDL', '0208', 'Laboratorio', 24, '20 a 30', TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDL', '0209', 'Laboratorio', 30, '20 a 30', TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDL', '0301', 'Laboratorio', 24, '20 a 30', TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDL', '0302', 'Laboratorio', 24, '20 a 30', TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDL', '0303', 'Laboratorio', 24, '20 a 30', TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDL', '0304', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Coordinación de Doctorado en Tecnologías de la Información. Departamento de Sistemas de Información (Sala de Juntas) y Doctorado en Tecnologías de la Información (Alumnos).'),
('CEDL', '0305', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Coordinación de Doctorado en Tecnologías de la Información.'),
('CEDL', '0306', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Espacio para alumnado de Doctorado de Sistemas..'),
('CEDL', '0308', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Departamento de Sistemas de Información.'),

-- Edificio M

('CEDM', '0101', 'Aula', 40, '30 a 40', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, 'Laboratorio de Matemáticas'),
('CEDM', '0102', 'Aula', 40, '30 a 40', TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDM', '0103', 'Aula', 26, '30 a 40', TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDM', '0104', 'Aula', 28, '30 a 40', TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDM', '0105', 'Aula', 38, '30 a 40', TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDM', '0106', 'Aula', 34, '30 a 40', TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDM', '0107', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Laboratorio para la Solución de Conflictos y Prevención de Violencias.'),
('CEDM', '0108', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Centro Público de Mediación. Departamento de Ciencias Sociales y Jurídicas.'),
('CEDM', '0201', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Oficina Departamento de Metodos Cuantitativos y Oficina Departamento Ciencias Sociales y Juridicas.'),
('CEDM', '0301', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Oficina Central INECER'),

-- Edificio N

('CEDN', '0101', 'Laboratorio', 24, '20 a 30', TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDN', '0102', 'Laboratorio', 24, '20 a 30', TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDN', '0103', 'Aula', 50, '40 a 50', TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDN', '0104', 'Aula', 44, '40 a 50', TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDN', '0105', 'Aula', 56, '40 a 50', TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDN', '0106', 'Aula', 45, '40 a 50', TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDN', '0107', 'Aula', 47, '40 a 50', TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDN', '0108', 'Aula', 45, '40 a 50', TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, ''),
('CEDN', '0200', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Unidad de protocolo.'),
('CEDN', '0201', 'Aula', 37, '30 a 40', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDN', '0202', 'Aula', 27, '20 a 30', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDN', '0203', 'Aula', 27, '20 a 30', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDN', '0204', 'Aula', 28, '20 a 30', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDN', '0205', 'Aula', 29, '20 a 30', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDN', '0206A', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Departamento de Estudios Regionales (INESR).'),
('CEDN', '0206', 'Laboratorio', 24, '20 a 30', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDN', '0207', 'Aula', 29, '20 a 30', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDN', '0208', 'Aula', 29, '20 a 30', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDN', '0209', 'Aula', 32, '20 a 30', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDN', '0210', 'Aula', 28, '20 a 30', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDN', '0211', 'Aula', 27, '30 a 40', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDN', '0212', 'Aula', 28, '30 a 40', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDN', '0213', 'Aula', 34, '30 a 40', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDN', '0300', 'Aula', 16, '15 a 20', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDN', '0301', 'Aula', 34, '30 a 40', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDN', '0302', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Language Program. Atención a profesores de idiomas.'),
('CEDN', '0304', 'Oficina Administrativa', 'N/A', 'N/A', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, ' Coordinacion de PALE - Programa CUCEA Global - Coordinador Unidad de Intercambio'),
('CEDN', '0305', 'Aula', 27, '20 a 30', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDN', '0306', 'Aula', 31, '20 a 30', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDN', '0307', 'Aula', 23, '20 a 30', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDN', '0308', 'Aula', 33, '30 a 40', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDN', '0309', 'Aula', 33, '30 a 40', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDN', '0310', 'Aula', 30, '20 a 30', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),
('CEDN', '0311', 'Aula', 34, '30 a 40', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, ''),

-- Aulas Amplias

('CEDAA', '0001', 'Aula Amplia', 150, '100 a 150', TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 'Aula Amplia 0001A, 0001B y 0001C'),
('CEDAA', '0002', 'Aula Amplia', 150, '100 a 150', TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 'Aula Amplia 0002A, 0002B y 0002C'),
('CEDAA', '0003', 'Aula Amplia', 150, '100 a 150', TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 'Aula Amplia 03'),
('CEDAA', '0004', 'Aula Amplia', 150, '100 a 150', TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 'Aula Amplia 0004A, 0004B y 0004C'),
('CEDAA', '0005', 'Aula Amplia', 150, '100 a 150', TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 'Aula Amplia 05'),
('CEDAA', '0006', 'Aula Amplia', 150, '100 a 150', TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 'Aula Amplia 06')";


if (mysqli_query($conexion, $espacios)) {
    echo "<br>Datos insertados exitosamente en la tabla Espacios";
} else {
    echo "<br>Error insertando Espacios: " . mysqli_error($conexion);
}
